//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceUA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceUA() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceUA", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дія.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нова подія.
        /// </summary>
        internal static string AddEvent {
            get {
                return ResourceManager.GetString("AddEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати свій запис.
        /// </summary>
        internal static string AddMyself {
            get {
                return ResourceManager.GetString("AddMyself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати нову лабораторну роботу.
        /// </summary>
        internal static string AddNewLab {
            get {
                return ResourceManager.GetString("AddNewLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати фото.
        /// </summary>
        internal static string AddPhoto {
            get {
                return ResourceManager.GetString("AddPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати власне завдання.
        /// </summary>
        internal static string AddTaskMyself {
            get {
                return ResourceManager.GetString("AddTaskMyself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати себе до списку студентів.
        /// </summary>
        internal static string AddToStudentList {
            get {
                return ResourceManager.GetString("AddToStudentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всі повідомленя на дану тему.
        /// </summary>
        internal static string AllMessages {
            get {
                return ResourceManager.GetString("AllMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всього запитань.
        /// </summary>
        internal static string AllQuestions {
            get {
                return ResourceManager.GetString("AllQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Програмістам різного рівня не залежно від досвіду програмування і віддає перевагу мови програмування.
        /// </summary>
        internal static string Audience1 {
            get {
                return ResourceManager.GetString("Audience1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Студентам вищих навчальних закладів ІТ-спеціальностей.
        /// </summary>
        internal static string Audience2 {
            get {
                return ResourceManager.GetString("Audience2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аналітикам для кращого розуміння процесів розробки ПЗ.
        /// </summary>
        internal static string Audience3 {
            get {
                return ResourceManager.GetString("Audience3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизація.
        /// </summary>
        internal static string Authorization {
            get {
                return ResourceManager.GetString("Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інформація про обліковий запис.
        /// </summary>
        internal static string AuthorizationInfo {
            get {
                return ResourceManager.GetString("AuthorizationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категорія.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва категорії.
        /// </summary>
        internal static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Змінити пароль.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зміна пароля не вдалася. Будь ласка, виправте помилки і повторіть спробу..
        /// </summary>
        internal static string ChangePasswordFailed {
            get {
                return ResourceManager.GetString("ChangePasswordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Змінити завдання.
        /// </summary>
        internal static string ChangeTask {
            get {
                return ResourceManager.GetString("ChangeTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підтвердіть новий пароль.
        /// </summary>
        internal static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підтвердіть пароль.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правильних відповідей.
        /// </summary>
        internal static string CorrectQuestions {
            get {
                return ResourceManager.GetString("CorrectQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Країна.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата створення.
        /// </summary>
        internal static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створення завдання для лабораторної роботи.
        /// </summary>
        internal static string CreateLab {
            get {
                return ResourceManager.GetString("CreateLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Залишити повідомлення.
        /// </summary>
        internal static string CreateMess {
            get {
                return ResourceManager.GetString("CreateMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити нову тему в цій категорії.
        /// </summary>
        internal static string CreateTheme {
            get {
                return ResourceManager.GetString("CreateTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створення новий облікового запису.
        /// </summary>
        internal static string CreatingAccount {
            get {
                return ResourceManager.GetString("CreatingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити із списку студентів.
        /// </summary>
        internal static string DeleteStudent {
            get {
                return ResourceManager.GetString("DeleteStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дистанційне навчання.
        /// </summary>
        internal static string DistantLearning {
            get {
                return ResourceManager.GetString("DistantLearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дистанційне навчання трактують як:.
        /// </summary>
        internal static string DLIs {
            get {
                return ResourceManager.GetString("DLIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цілеспрямоване і методично організоване керівництво
        ///        навчально-пізнавальною діяльністю осіб, що знаходяться на відстані від освітнього
        ///        центру, яке відбувається завдяки електронним і традиційним засобам зв&apos;язку..
        /// </summary>
        internal static string DLIs1 {
            get {
                return ResourceManager.GetString("DLIs1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Процес
        ///        отримання знань і навичок за допомогою спеціалізованого освітнього середовища, яке
        ///        основане на використанні ІТ, що забезпечує обмін навчальною інформацією на відстані
        ///        і реалізує систему супроводу і адміністрування учбовим процесом..
        /// </summary>
        internal static string DLIs2 {
            get {
                return ResourceManager.GetString("DLIs2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (англ. Distant learning) — Новий засіб реалізації процесу навчання, в основі якого
        ///        використання сучасних інформаційних і телекомунікаційних технологій, що дозволяють
        ///        навчатись на відстані без безпосереднього, особистого контакту між викладачем і
        ///        учнем..
        /// </summary>
        internal static string DLText {
            get {
                return ResourceManager.GetString("DLText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Першопочатково дистанційне навчання здіснювалась у формі письмового спілкування,
        ///        тт. розв&apos;язані завдання відсилались поштою. На сучасному етапі дистанційне навчання
        ///        здійснюється також за допомогою інтернету, доступом до мережевих баз даних тощо..
        /// </summary>
        internal static string DLText1 {
            get {
                return ResourceManager.GetString("DLText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагувати.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спроба пристосувати зміни виявилася безуспішною. Будь ласка, виправте помилки і спробуйте ще раз..
        /// </summary>
        internal static string EditWasUnsuccessful {
            get {
                return ResourceManager.GetString("EditWasUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Освіта.
        /// </summary>
        internal static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будь ласка, виправте помилки і спробуйте ще раз..
        /// </summary>
        internal static string ErrorsInData {
            get {
                return ResourceManager.GetString("ErrorsInData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Події.
        /// </summary>
        internal static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вихід.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зворотній зв&apos;язок.
        /// </summary>
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обговорення.
        /// </summary>
        internal static string Forum {
            get {
                return ResourceManager.GetString("Forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти до списку лабораторних робіт.
        /// </summary>
        internal static string GoToLabList {
            get {
                return ResourceManager.GetString("GoToLabList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти до результатів тестування.
        /// </summary>
        internal static string GoToProgressList {
            get {
                return ResourceManager.GetString("GoToProgressList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Якщо не маєте власного облікового запису, ви маєте можливість.
        /// </summary>
        internal static string IfYouHaventAccount {
            get {
                return ResourceManager.GetString("IfYouHaventAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to символів у довжину..
        /// </summary>
        internal static string InLenght {
            get {
                return ResourceManager.GetString("InLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть необхідні зміни.
        /// </summary>
        internal static string InsertChanges {
            get {
                return ResourceManager.GetString("InsertChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заповніть поля для створення повідомлення.
        /// </summary>
        internal static string InsertColumnsForMess {
            get {
                return ResourceManager.GetString("InsertColumnsForMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть всі необхідні дані..
        /// </summary>
        internal static string InsertData {
            get {
                return ResourceManager.GetString("InsertData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть оцінки.
        /// </summary>
        internal static string InsertMarks {
            get {
                return ResourceManager.GetString("InsertMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть своє ім&apos;я користувача і пароль.
        /// </summary>
        internal static string InsertUsenamePassword {
            get {
                return ResourceManager.GetString("InsertUsenamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лабораторна робота №1.
        /// </summary>
        internal static string Lab1 {
            get {
                return ResourceManager.GetString("Lab1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лабораторна робота №2.
        /// </summary>
        internal static string Lab2 {
            get {
                return ResourceManager.GetString("Lab2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лабораторна робота №3.
        /// </summary>
        internal static string Lab3 {
            get {
                return ResourceManager.GetString("Lab3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список лабораторних робіт.
        /// </summary>
        internal static string LabList {
            get {
                return ResourceManager.GetString("LabList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завдання.
        /// </summary>
        internal static string Labs {
            get {
                return ResourceManager.GetString("Labs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список тем.
        /// </summary>
        internal static string ListThemes {
            get {
                return ResourceManager.GetString("ListThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Короткі відомості.
        /// </summary>
        internal static string LittleInfo {
            get {
                return ResourceManager.GetString("LittleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загальні відомості.
        /// </summary>
        internal static string LittleText {
            get {
                return ResourceManager.GetString("LittleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загальне.
        /// </summary>
        internal static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальна оцінка.
        /// </summary>
        internal static string MaxMark {
            get {
                return ResourceManager.GetString("MaxMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повідомлення.
        /// </summary>
        internal static string Mess {
            get {
                return ResourceManager.GetString("Mess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повідомлення на тему.
        /// </summary>
        internal static string MessOnTheme {
            get {
                return ResourceManager.GetString("MessOnTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По батькові.
        /// </summary>
        internal static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детально.
        /// </summary>
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прізвище.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва теми повинна бути більшою ніж 3 символи.
        /// </summary>
        internal static string NameOfThemeTaskIsShort {
            get {
                return ResourceManager.GetString("NameOfThemeTaskIsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва теми.
        /// </summary>
        internal static string NameTheme {
            get {
                return ResourceManager.GetString("NameTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нова тема.
        /// </summary>
        internal static string NewTheme {
            get {
                return ResourceManager.GetString("NewTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новини нашого центру.
        /// </summary>
        internal static string OurNews {
            get {
                return ResourceManager.GetString("OurNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш пароль був успішно змінений..
        /// </summary>
        internal static string PasswordAreChanged {
            get {
                return ResourceManager.GetString("PasswordAreChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новий пароль.
        /// </summary>
        internal static string PasswordNew {
            get {
                return ResourceManager.GetString("PasswordNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поточний пароль.
        /// </summary>
        internal static string PasswordOld {
            get {
                return ResourceManager.GetString("PasswordOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 609052290.
        /// </summary>
        internal static string PasswordOOP {
            get {
                return ResourceManager.GetString("PasswordOOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Персональне завдання.
        /// </summary>
        internal static string PersonalTask {
            get {
                return ResourceManager.GetString("PersonalTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контактний телефон.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посада.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Професія.
        /// </summary>
        internal static string Profession {
            get {
                return ResourceManager.GetString("Profession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Питання.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактор питань.
        /// </summary>
        internal static string QuestionEditor {
            get {
                return ResourceManager.GetString("QuestionEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Варіанти відповідей.
        /// </summary>
        internal static string QuestionVariants {
            get {
                return ResourceManager.GetString("QuestionVariants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відповісти/Запитати.
        /// </summary>
        internal static string Question_answer {
            get {
                return ResourceManager.GetString("Question_answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити обліковий запис не вдалося. Будь ласка, виправте помилки і повторіть спробу.
        /// </summary>
        internal static string RegistrationFailed {
            get {
                return ResourceManager.GetString("RegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інформація про реєстрацію.
        /// </summary>
        internal static string RegistrationInformation {
            get {
                return ResourceManager.GetString("RegistrationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        internal static string RegistrationUserPassword {
            get {
                return ResourceManager.GetString("RegistrationUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запам&apos;ятати мене?.
        /// </summary>
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат.
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я.
        /// </summary>
        internal static string SecondName {
            get {
                return ResourceManager.GetString("SecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть категорію.
        /// </summary>
        internal static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вибачте, сталася помилка при обробці запиту.
        /// </summary>
        internal static string SorryQuerrey {
            get {
                return ResourceManager.GetString("SorryQuerrey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Призначення.
        /// </summary>
        internal static string Specificity {
            get {
                return ResourceManager.GetString("Specificity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розпочати тест з ООП.
        /// </summary>
        internal static string StartTestop {
            get {
                return ResourceManager.GetString("StartTestop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть обов&apos;язкові дані для реєстрації..
        /// </summary>
        internal static string Status_EnterData {
            get {
                return ResourceManager.GetString("Status_EnterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка. Заповніть коректно дані, введіть пароль виданий керівником..
        /// </summary>
        internal static string Status_Error {
            get {
                return ResourceManager.GetString("Status_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ООП.
        /// </summary>
        internal static string stringCategoryOop {
            get {
                return ResourceManager.GetString("stringCategoryOop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список студентів.
        /// </summary>
        internal static string StudentList {
            get {
                return ResourceManager.GetString("StudentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оцінки студента.
        /// </summary>
        internal static string StudentMarks {
            get {
                return ResourceManager.GetString("StudentMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успішність студентів які проходять курс навчання.
        /// </summary>
        internal static string StudentProgressList {
            get {
                return ResourceManager.GetString("StudentProgressList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Студенти.
        /// </summary>
        internal static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список завдань.
        /// </summary>
        internal static string TaskList {
            get {
                return ResourceManager.GetString("TaskList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Узгодження робіт.
        /// </summary>
        internal static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тест.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результати тестування.
        /// </summary>
        internal static string TestResults {
            get {
                return ResourceManager.GetString("TestResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тестування.
        /// </summary>
        internal static string Tests {
            get {
                return ResourceManager.GetString("Tests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для того, щоб почати проходження тестів, не обов&apos;язково мати багато досвіду 
        ///        в проектуванні і програмуванні. Більшість тестів з цієї категорії розбиті на 
        ///        3 рівні складності, тому кожна людина знайде тест, який максимально йому походить..
        /// </summary>
        internal static string TextTargetAudience {
            get {
                return ResourceManager.GetString("TextTargetAudience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ні для кого не секрет, що мови програмування високого рівня набирають все більшої
        ///        популярності. І звичайно ж основним підходом у розробці програмного забезпечення
        ///        на високорівневих мовах є об&apos;єктно-орієнтований підхід. Об&apos;єктно-орієнтований підхід
        ///        дозволяє створювати більш якісні програми, які легко супроводжувати і розвивати.
        ///        Основи ООП повинен знати кожен програміст, інструментом якого є такі мови програмування
        ///        як: PHP, Java, C + +, C #, Delphi і так далі..
        /// </summary>
        internal static string TextTestInfo {
            get {
                return ResourceManager.GetString("TextTestInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нові паролі повинні бути не менш.
        /// </summary>
        internal static string TheLenghtOfPAssword {
            get {
                return ResourceManager.GetString("TheLenghtOfPAssword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тести даної категорії будуть цікаві наступним людям:.
        /// </summary>
        internal static string TitleAudience {
            get {
                return ResourceManager.GetString("TitleAudience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перелік лабораторних робіт.
        /// </summary>
        internal static string TitleLabList {
            get {
                return ResourceManager.GetString("TitleLabList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цільова аудиторія тестів з ООП.
        /// </summary>
        internal static string TitleTargetAudience {
            get {
                return ResourceManager.GetString("TitleTargetAudience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Онлайн тестування з ООП.
        /// </summary>
        internal static string TitleTestInfo {
            get {
                return ResourceManager.GetString("TitleTestInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to зареєструватися.
        /// </summary>
        internal static string ToRegister {
            get {
                return ResourceManager.GetString("ToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Місто.
        /// </summary>
        internal static string Town {
            get {
                return ResourceManager.GetString("Town", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Змінити завдання.
        /// </summary>
        internal static string UpdateLab {
            get {
                return ResourceManager.GetString("UpdateLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Використовуйте форму нижче, щоб змінити свій пароль.
        /// </summary>
        internal static string UseChangePasswordForm {
            get {
                return ResourceManager.GetString("UseChangePasswordForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Використовуйте форму нижче, щоб створити новий обліковий запис.
        /// </summary>
        internal static string UseNextForms {
            get {
                return ResourceManager.GetString("UseNextForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувач.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я користувача.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перегляд успішності.
        /// </summary>
        internal static string ViewProgressList {
            get {
                return ResourceManager.GetString("ViewProgressList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ласкаво просимо.
        /// </summary>
        internal static string welcom {
            get {
                return ResourceManager.GetString("welcom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ласкаво просимо до нашого сайту.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вірна відповідь.
        /// </summary>
        internal static string WrightAnswer {
            get {
                return ResourceManager.GetString("WrightAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірна відповідь №1.
        /// </summary>
        internal static string WrongAnswer1 {
            get {
                return ResourceManager.GetString("WrongAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірна відповідь №2.
        /// </summary>
        internal static string WrongAnswer2 {
            get {
                return ResourceManager.GetString("WrongAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірна відповідь №3.
        /// </summary>
        internal static string WrongAnswer3 {
            get {
                return ResourceManager.GetString("WrongAnswer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рік народження.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ваше тестування завершено.
        /// </summary>
        internal static string YourTestCompllete {
            get {
                return ResourceManager.GetString("YourTestCompllete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Незадовільно.
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задовільно.
        /// </summary>
        internal static string _3 {
            get {
                return ResourceManager.GetString("_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добре.
        /// </summary>
        internal static string _4 {
            get {
                return ResourceManager.GetString("_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відмінно.
        /// </summary>
        internal static string _5 {
            get {
                return ResourceManager.GetString("_5", resourceCulture);
            }
        }
    }
}
