<?xml version="1.0" encoding="utf-8"?>
<Database Name="MVCdb" Class="MVCbugDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=MICROSOF-57E36E;Initial Catalog=MVCdb;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MVCdbConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Themes" Member="Themes">
    <Type Name="Theme">
      <Column Name="ThemeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ThemeName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CategoryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AssignedOn" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Tests" Member="Tests">
    <Type Name="Test">
      <Column Name="TestId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="AnswersCorrectly" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AnswersAll" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Began" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Finished" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="aspnet_User_Test" Member="aspnet_User" ThisKey="UserId" Type="aspnet_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tasks" Member="Tasks">
    <Type Name="Task">
      <Column Name="TaskId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="StateId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AssignedOn" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="State_Task" Member="State" ThisKey="StateId" Type="State" IsForeignKey="true" />
      <Association Name="aspnet_User_Task" Member="aspnet_User" ThisKey="AssignedOn" Type="aspnet_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Students" Member="Students">
    <Type Name="Student">
      <Column Name="StudentId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SecondName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MiddleName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="BornYear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Profession" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Position" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Town" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EducationType" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Student_LabResult" Member="LabResults" OtherKey="StudentId" Type="LabResult" />
      <Association Name="aspnet_User_Student" Member="aspnet_User" ThisKey="UserId" Type="aspnet_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.States" Member="States">
    <Type Name="State">
      <Column Name="StateId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Association Name="State_Task" Member="Tasks" OtherKey="StateId" Type="Task" />
    </Type>
  </Table>
  <Table Name="dbo.Questions" Member="Questions">
    <Type Name="Question">
      <Column Name="QuestionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Question" Member="Question1" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="Answer" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="Answer1" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="Answer2" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="Answer3" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Messages" Member="Messages">
    <Type Name="Message">
      <Column Name="MessageId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="AnswerTo" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="DateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ThemeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CategoryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="Category_Message" Member="Category" ThisKey="CategoryId" Type="Category" IsForeignKey="true" />
      <Association Name="aspnet_User_Message" Member="aspnet_User" ThisKey="UserId" Type="aspnet_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Labs" Member="Labs">
    <Type Name="Lab">
      <Column Name="LabId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CategoryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Category_Lab" Member="Category" ThisKey="CategoryId" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LabResults" Member="LabResults">
    <Type Name="LabResult">
      <Column Name="ResultLabId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Lab1" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="Lab2" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="Lab3" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="StudentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Student_LabResult" Member="Student" ThisKey="StudentId" Type="Student" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EventStates" Member="EventStates">
    <Type Name="EventState">
      <Column Name="StateId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="EventState_Event" Member="Events" OtherKey="StateId" Type="Event" />
    </Type>
  </Table>
  <Table Name="dbo.Events" Member="Events">
    <Type Name="Event">
      <Column Name="EventId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="StateId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Specificity" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="EventState_Event" Member="EventState" ThisKey="StateId" Type="EventState" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Categories" Member="Categories">
    <Type Name="Category">
      <Column Name="CategoryId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Category_Message" Member="Messages" OtherKey="CategoryId" Type="Message" />
      <Association Name="Category_Lab" Member="Labs" OtherKey="CategoryId" Type="Lab" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Users" Member="aspnet_Users">
    <Type Name="aspnet_User">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredUserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="MobileAlias" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="IsAnonymous" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastActivityDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_User_Test" Member="Tests" OtherKey="UserId" Type="Test" />
      <Association Name="aspnet_User_Task" Member="Tasks" OtherKey="AssignedOn" Type="Task" />
      <Association Name="aspnet_User_Student" Member="Students" OtherKey="UserId" Type="Student" />
      <Association Name="aspnet_User_Message" Member="Messages" OtherKey="UserId" Type="Message" />
    </Type>
  </Table>
</Database>